In [1]:

import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split

from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.optimizers import SGD
from keras.utils import np_utils
from keras.callbacks import LearningRateScheduler
from keras.constraints import maxnorm
from keras.regularizers import l2
from random import shuffle

from matplotlib import pyplot as plt
%matplotlib inline

import cv2
import glob
import os
import re

/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using TensorFlow backend.


In [0]:
from google.colab import drive

In [4]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
positive_path = "/content/drive/My Drive/Colab_Folder/SMILES/positives"
negative_path = "/content/drive/My Drive/Colab_Folder/SMILES/negatives"

ROWS = 32
COLS = 32
CHANNELS = 1

# images = [img for img in os.listdir(train_path)]
images_pos = [img for img in os.listdir(positive_path)]
images_neg = [img for img in os.listdir(negative_path)]


print(images_pos[:10])
print(images_neg[:10])

ps = len(images_pos)
ng = len(images_neg)
tot = ps + ng

data = np.ndarray(shape=(tot,ROWS, COLS))
labels = np.ndarray(tot)

for t in range(0,tot):
  if t < ps:
    for i, img_path in enumerate(images_pos):
#       print("pos")
#       print(i)
      img_pos = cv2.imread(os.path.join(positive_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_pos = cv2.resize(img_pos, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
    
      data[i] = img_pos
      labels[i] = 1
      
  elif t >= ps & t <= tot:
    for i, img_path in enumerate(images_neg):
#       print("neg")
#       print(i)
      img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_neg = cv2.resize(img_neg, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
  
      data[ps + i] = img_neg
      labels[ps + i] = 0
      
      
# for i, img_path in enumerate(images_pos):
#     print("pos")
#     print(i)
#     img_pos = cv2.imread(os.path.join(positive_path, img_path), 0)
# #     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
#     img_pos = cv2.resize(img_pos, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
    
#     pos[i] = img_pos
#     labels_pos[i] = 1

    
# neg = np.ndarray(shape=(len(images_neg),ROWS, COLS))
# labels_neg = np.ndarray(len(images_neg))

# for i, img_path in enumerate(images_neg):
#     print("neg")
#     print(i)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
# #     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
#     img_neg = cv2.resize(img_neg, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
    
#     neg[i] = img_neg
#     labels_neg[i] = 0
    
    

    
# for i in range(0, )
    
# data = pos + neg
# labels = labels_pos + labels_neg

['6649.jpg', '6654.jpg', '6670.jpg', '6666.jpg', '6669.jpg', '668.jpg', '6657.jpg', '6668.jpg', '6681.jpg', '6674.jpg']
['8752.jpg', '8765.jpg', '8763.jpg', '8764.jpg', '8768.jpg', '8767.jpg', '8776.jpg', '8778.jpg', '8774.jpg', '8771.jpg']


In [0]:
ps = len(images_pos)
ng = len(images_neg)
tot = ps + ng

data = np.ndarray(shape=(tot,ROWS, COLS))
labels = np.ndarray(tot)


for t in range(0,tot):
  if t < ps:
    data[t] = pos[t]
    labels[t] = labels_pos[t]
    
        
  elif t >= ps & t <= tot:
      data[t] = neg[t-ps]
      labels[t] = labels_neg[t-ps]
  

In [5]:
# data.shape
data[:10]

NameError: ignored

In [28]:
img_pos_smpl = images_pos[:10]
img_neg_smpl = images_neg[:10]
print(img_pos_smpl)
print(img_neg_smpl)

['6649.jpg', '6654.jpg', '6670.jpg', '6666.jpg', '6669.jpg', '668.jpg', '6657.jpg', '6668.jpg', '6681.jpg', '6674.jpg']
['8752.jpg', '8765.jpg', '8763.jpg', '8764.jpg', '8768.jpg', '8767.jpg', '8776.jpg', '8778.jpg', '8774.jpg', '8771.jpg']


In [30]:
ps = len(img_pos_smpl)
ng = len(img_neg_smpl)
tot = ps + ng
print(tot)

dt = np.ndarray(shape=(tot,ROWS, COLS))
lbls = np.ndarray(tot)

20


In [33]:


for t in range(0,tot):
  if t <= ps:
    for i, img_path in enumerate(img_pos_smpl):
      print("pos")
      print(i)
      img_pos = cv2.imread(os.path.join(positive_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_pos = cv2.resize(img_pos, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
    
      dt[i] = img_pos
      lbls[i] = 1
      
  elif t > ps & t <= tot:
    for i, img_path in enumerate(img_neg_smpl):
      print("neg")
      print(i)
      img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_neg = cv2.resize(img_neg, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
  
      dt[ps + i] = img_neg
      lbls[ps + i] = 0
  

pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
pos
0
pos
1
pos
2
pos
3
pos
4
pos
5
pos
6
pos
7
pos
8
pos
9
neg
0
neg
1
neg
2
neg
3
neg
4
neg
5
neg
6
neg
7
neg
8
neg
9
neg
0
neg
1
neg
2
neg
3
neg
4
neg
5
neg
6
neg
7
neg
8
neg
9
neg
0
neg
1
neg
2
neg
3
neg
4
neg
5
neg
6
neg
7
neg
8
neg
9
neg
0
neg
1
neg
2
neg
3
neg
4
neg
5
neg
6
neg
7
neg
8
neg
9
neg
0
neg
1
neg
2
neg
3
neg
4
neg
5
neg
6
neg
7
neg
8
neg
9
neg
0
neg
1
neg
2
neg
3
neg
4
neg
5
neg


In [0]:
for t in range(0,tot):
  if t <= ps:
    for i, img_path in enumerate(img_pos_smpl):
      print("pos")
      print(i)
      img_pos = cv2.imread(os.path.join(positive_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_pos = cv2.resize(img_pos, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
    
      dt[i] = img_pos
      lbls[i] = 1
      
  elif t > ps & t <= tot:
    for i, img_path in enumerate(img_neg_smpl):
      print("neg")
      print(i)
      img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_neg = cv2.resize(img_neg, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
  
      dt[ps + i] = img_pos
      lbls[ps + i] = 0

In [35]:
dt.shape

(20, 128, 128)

In [26]:
train_list[:10]

['positives', 'negatives']

In [0]:
ps = len(images_pos)
ng = len(images_neg)
tot = ps + ng

data = np.ndarray(shape=(len(tot),ROWS, COLS))
labels = np.ndarray(len(tot))

for t in range(0,tot):
  if t <= ps:
    for i, img_path in enumerate(images_pos):
      print("pos")
      print(i)
      img_pos = cv2.imread(os.path.join(positive_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_pos = cv2.resize(img_pos, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
    
      data[i] = img_pos
      labels[i] = 1
      
  elif t > ps & t <= tot:
    for i, img_path in enumerate(images_neg):
      print("neg")
      print(i)
      img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
#     img_neg = cv2.imread(os.path.join(negative_path, img_path), 0)
      img_neg = cv2.resize(img_neg, (ROWS, COLS), interpolation=cv2.INTER_CUBIC)
  

In [40]:
sample = data[:100]

sample1 = np.array(sample).reshape((-1, 1, 128, 128)).astype('float32')
# print(labels[:10])
sample1.shape

(100, 1, 128, 128)

In [48]:
np.unique(labels)

array([0., 1.])

In [47]:
labels.astype('int')

array([1, 1, 1, ..., 0, 0, 0])

shuffling data

In [0]:
## dividing by 255
data /= 255

In [0]:
ind_list = [i for i in range(tot)]
shuffle(ind_list)
data_new  = data[ind_list,]
labels_new = labels[ind_list,]

In [51]:
labels_new[:15]

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.])

In [57]:
data_new.shape

(13165, 128, 128)

In [0]:
data_new = np.array(data_new).reshape((-1, 1, 128, 128)).astype('float32')
# print(labels[:10])

In [59]:
data_new.shape

(13165, 1, 128, 128)